# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'navigationlogin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for navigationlogin

  target 'navigationloginTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'navigationloginUITests' do
    # Pods for testing
  end

	pod 'Firebase/Core'
	pod 'Firebase/Database'
	pod 'Firebase/Auth'

end
